### ISSUE TITLE
Spider: Creve Coeur Venable Park Task Force

### ISSUE THREAD

**Issue by bchao99** [stl-public-meetings/city-scrapers-stl#1]
URL: https://crevecoeurcitymo.iqm2.com/Citizens/Calendar.aspx?From=1%2f1%2f1900&To=12%2f31%2f9999
Spider Name: cc_venable_park
Agency Name: Creve Coeur Venable Park Task Force
See the contribution guide for information on how to get started

**Comment by ledaliang** [comment]
Meme and I can get started on this spider
