### ISSUE TITLE
Spider: Creve Coeur Stormwater Committee

### ISSUE THREAD

**Issue by bchao99** [stl-public-meetings/city-scrapers-stl#2]
URL: https://crevecoeurcitymo.iqm2.com/Citizens/Calendar.aspx?From=1%2f1%2f1900&To=12%2f31%2f9999
Spider Name: cc_stormwater
Agency Name: Creve Coeur Stormwater Committee
See the contribution guide for information on how to get started

**Comment by meme1015** [comment]
I'll start on this issue
