### ISSUE TITLE
Spider: St. Louis Land Clearance for Redevelopment Authority

### ISSUE THREAD

**Issue by bchao99** [stl-public-meetings/city-scrapers-stl#40]
URL: [https://www.stlouis-mo.gov/government/departments/sldc/boards/Land-Clearance-for-Redevelopment-Authority.cfm](https://www.stlouis-mo.gov/government/departments/sldc/boards/Land-Clearance-for-Redevelopment-Authority.cfm)
Spider Name: `stl_redevelopment`
Agency Name: SLDC Development Boards

See the [contribution guide](https://github.com/stl-public-meetings/city-scrapers-stl/blob/main/CONTRIBUTING.md) for information on how to get started

**Comment by ledaliang** [comment]
I am going to work on this spider.
