### ISSUE TITLE
Spider: St. Louis Clean Energy Development Board

### ISSUE THREAD

**Issue by bchao99** [stl-public-meetings/city-scrapers-stl#41]
URL: [https://www.stlouis-mo.gov/government/departments/sldc/boards/Clean-Energy-Development-Board.cfm](https://www.stlouis-mo.gov/government/departments/sldc/boards/Clean-Energy-Development-Board.cfm)
Spider Name: stl_energy_development
Agency Name: SLDC Development Boards

See the [contribution guide](https://github.com/stl-public-meetings/city-scrapers-stl/blob/main/CONTRIBUTING.md) for information on how to get started

**Comment by ledaliang** [comment]
I think the agency name should be St. Louis Clean Energy Development Board, and we can omit "Quarterly Board Meeting" from each meeting title.

**Comment by ledaliang** [comment]
The links returned should be a direct link to the document instead of the website where the documents are posted. I can fix this if you want.
