### ISSUE TITLE
Spider: St. Louis Enhanced Enterprise Zone Board

### ISSUE THREAD

**Issue by bchao99** [stl-public-meetings/city-scrapers-stl#42]
URL: [https://www.stlouis-mo.gov/government/departments/sldc/boards/enhanced-enterprise-zone-commission-july-26-2016.cfm](https://www.stlouis-mo.gov/government/departments/sldc/boards/enhanced-enterprise-zone-commission-july-26-2016.cfm)
Spider Name: `stl_enterprise_zone`
Agency Name: St. Louis Enhanced Enterprise Zone Board

See the [contribution guide](https://github.com/stl-public-meetings/city-scrapers-stl/blob/main/CONTRIBUTING.md) for information on how to get started

**Comment by ledaliang** [comment]
I'm going to work on this spider
