### ISSUE TITLE
Spider: St. Louis Industrial Development Authority

### ISSUE THREAD

**Issue by bchao99** [stl-public-meetings/city-scrapers-stl#43]
URL: [https://www.stlouis-mo.gov/government/departments/sldc/boards/Industrial-Development-Authority.cfm](https://www.stlouis-mo.gov/government/departments/sldc/boards/Industrial-Development-Authority.cfm)
Spider Name: `stl_industrial_development`
Agency Name: St. Louis Industrial Development Authority

See the [contribution guide](https://github.com/stl-public-meetings/city-scrapers-stl/blob/main/CONTRIBUTING.md) for information on how to get started

**Comment by ledaliang** [comment]
I'm going to start working on this spider.
