### ISSUE TITLE
Spider: St. Louis Land Reutilization Authority

### ISSUE THREAD

**Issue by bchao99** [stl-public-meetings/city-scrapers-stl#44]
URL: [https://www.stlouis-mo.gov/government/departments/sldc/boards/Land-Reutilization-Authority.cfm](https://www.stlouis-mo.gov/government/departments/sldc/boards/Land-Reutilization-Authority.cfm)
Spider Name: `stl_land_reutilization`
Agency Name: St. Louis Land Reutilization Authority

See the [contribution guide](https://github.com/stl-public-meetings/city-scrapers-stl/blob/main/CONTRIBUTING.md) for information on how to get started

**Comment by ledaliang** [comment]
I can work on this spider.
