### ISSUE TITLE
Spider: St. Louis Local Development Company

### ISSUE THREAD

**Issue by bchao99** [stl-public-meetings/city-scrapers-stl#48]
URL: [https://www.stlouis-mo.gov/government/departments/sldc/boards/Local-Development-Company.cfm](https://www.stlouis-mo.gov/government/departments/sldc/boards/Local-Development-Company.cfm)
Spider Name: `stl_development`
Agency Name: St. Louis Local Development Company

See the [contribution guide](https://github.com/stl-public-meetings/city-scrapers-stl/blob/main/CONTRIBUTING.md) for information on how to get started

**Comment by ledaliang** [comment]
I can work on this spider.
