### ISSUE TITLE
Archive scraped pages and documents on the Wayback Machine

### ISSUE THREAD

**Issue by pjsier** [stl-public-meetings/city-scrapers-stl#58]
Great work getting this up and running so quickly! One of the aspects of the City Scrapers project we haven't documented very well is our use of a Python package we created, [`scrapy-wayback-middleware`](https://github.com/City-Bureau/scrapy-wayback-middleware).

The overall goal of the City Scrapers project is to improve transparency and create an archive not just of upcoming meetings, but past meetings and related documents as well as how they change over time. An important part of that for us has been archiving (almost) every page and document we scrape on the [Internet Archive's Wayback Machine](https://web.archive.org/) as well as in our static output.

Having a second, more public and accessible location makes the meeting information more available regardless of how long the project goes. We've even used it to track potential violations of open meetings laws, since it provides an external source for seeing what content was or was not on a website at a given time. Here's an example of [snapshots of the Chicago Plan Commission's website over time](https://web.archive.org/web/20200215000000*/https://chicago.gov/city/en/depts/dcd/supp_info/chicago_plan_commission.html).

The con of this approach is that it can make cron builds take significantly longer, but currently we're well under the 6 hour GitHub Actions time limit with over 100 scrapers on the main City Scrapers repo.

If you're interested, you can add `scrapy-wayback-middleware` as a dependency, and then you'll likely want to subclass the middleware to also scrape any documents you find like we've done in our main [`middleware.py`](https://github.com/City-Bureau/city-scrapers/blob/main/city_scrapers/middleware.py). Then you can add it in your `settings/prod.py` like we [did in our settings](https://github.com/City-Bureau/city-scrapers/blob/c6771d58209fa9ade4aa3768fa3ddb23b45c09fc/city_scrapers/settings/prod.py#L12-L16).

We're only activating it when the `WAYBACK_ENABLED` environment variable is set, and the template `cron.yml` file already sets this so once it's added in your settings file you should be good to go!

Let me know if you have any questions, and I'm happy to put in a PR for this if it's helpful

**Comment by ledaliang** [comment]
Hi Pat, this sounds great! Unfortunately, we're not very familiar with adding dependencies. Could you put in a PR for this?
