### ISSUE TITLE
Spider: St. Louis Mechanical Section

### ISSUE THREAD

**Issue by meme1015** [stl-public-meetings/city-scrapers-stl#60]
URL: https://www.stlouis-mo.gov/events/past-meetings.cfm?department=359
Spider Name: `stl_mechanical`
Agency Name: St. Louis Mechanical Section

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by ledaliang** [comment]
I can work on this spider.
