### ISSUE TITLE
Spider: Clayton Board Of Aldermen

### ISSUE THREAD

**Issue by meme1015** [stl-public-meetings/city-scrapers-stl#61]
URL: https://www.claytonmo.gov/government/mayor-board-of-aldermen
Calendar URL: https://www.claytonmo.gov/calendar/meetings/-toggle-all/-seldept-2
Spider Name: `clay_aldermen`
Agency Name: Clayton Board Of Aldermen

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by ledaliang** [comment]
I can work on this spider
